name: Blueprint check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: NPM Install
      run: npm install

    - name: Build contracts
      run: npx blueprint build

    - name: Run tests
      run: npx blueprint test
